"'HACT Configuration' As screen":
    LoadingSpinnerColor: =RGBA(105, 121, 126, 1)

    Component1_18 As Component1:
        CurrentScreen: ="Configuration"
        Height: =768

    Icon13 As icon.HorizontalLine:
        BorderColor: =RGBA(102, 102, 102, 1)
        BorderThickness: =1
        Color: =RGBA(102, 102, 102, 1)
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(220, 220, 220, 1)
        DisabledFill: =RGBA(0, 0, 0, 0)
        FocusedBorderThickness: =4
        Height: =1
        HoverBorderColor: =RGBA(0, 0, 0, 0)
        HoverColor: =ColorFade(RGBA(105, 121, 126, 1), -30%)
        HoverFill: =RGBA(0, 0, 0, 0)
        Icon: =Icon.HorizontalLine
        PaddingBottom: =10
        PaddingLeft: =10
        PaddingRight: =10
        PaddingTop: =10
        PressedBorderColor: =RGBA(0, 0, 0, 0)
        PressedColor: =ColorFade(RGBA(105, 121, 126, 1), -30%)
        PressedFill: =RGBA(0, 0, 0, 0)
        Width: =1039
        X: =303
        Y: =189
        ZIndex: =2

    Label13 As label:
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderStyle: =BorderStyle.None
        BorderThickness: =2
        Color: =RGBA(0, 18, 107, 1)
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(166, 166, 166, 1)
        FocusedBorderThickness: =4
        Font: =Font.'Segoe UI'
        FontWeight: =FontWeight.Bold
        Height: =58
        Size: =20
        Text: ="Supplier Happiness Survey Settings"
        Width: =550
        X: =291
        Y: =132
        ZIndex: =3

    Container3 As groupContainer.manualLayoutContainer:
        DropShadow: =DropShadow.Semilight
        Height: =528
        RadiusBottomLeft: =4
        RadiusBottomRight: =4
        RadiusTopLeft: =4
        RadiusTopRight: =4
        Width: =596
        X: =318
        Y: =213
        ZIndex: =4

        Rectangle4 As rectangle:
            BorderColor: =RGBA(0, 0, 0, 0)
            BorderStyle: =BorderStyle.None
            BorderThickness: =2
            DisabledFill: =RGBA(166, 166, 166, 1)
            Fill: =RGBA(237, 237, 237, 1)
            FocusedBorderThickness: =4
            Height: =56
            HoverFill: =RGBA(105, 121, 126, 1)
            PressedFill: =RGBA(105, 121, 126, 1)
            Width: =596
            ZIndex: =1

        Label15 As label:
            BorderColor: =RGBA(0, 0, 0, 0)
            BorderStyle: =BorderStyle.None
            BorderThickness: =2
            Color: =RGBA(51, 51, 51, 1)
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            DisabledColor: =RGBA(166, 166, 166, 1)
            FocusedBorderThickness: =4
            Font: =Font.'Segoe UI'
            FontWeight: =FontWeight.Semibold
            Height: =34
            Size: =17
            Text: ="Edit Configuration"
            Width: =538
            X: =13
            Y: =8
            ZIndex: =2

        Label16 As label:
            BorderColor: =RGBA(0, 0, 0, 0)
            BorderStyle: =BorderStyle.None
            BorderThickness: =2
            Color: =RGBA(51, 51, 51, 1)
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            DisabledColor: =RGBA(166, 166, 166, 1)
            FocusedBorderThickness: =4
            Font: =Font.'Segoe UI'
            Size: =13
            Text: |-
                ="Stakeholder:Supplier"
            Width: =191
            X: =24
            Y: =66
            ZIndex: =3

        Icon14 As icon.HorizontalLine:
            BorderColor: =RGBA(202, 202, 202, 1)
            BorderThickness: =1
            Color: =RGBA(202, 202, 202, 1)
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            DisabledColor: =RGBA(220, 220, 220, 1)
            DisabledFill: =RGBA(0, 0, 0, 0)
            FocusedBorderThickness: =4
            Height: =1
            HoverBorderColor: =RGBA(0, 0, 0, 0)
            HoverColor: =ColorFade(RGBA(105, 121, 126, 1), -30%)
            HoverFill: =RGBA(0, 0, 0, 0)
            Icon: =Icon.HorizontalLine
            PressedBorderColor: =RGBA(0, 0, 0, 0)
            PressedColor: =ColorFade(RGBA(105, 121, 126, 1), -30%)
            PressedFill: =RGBA(0, 0, 0, 0)
            Width: =567
            X: =20
            Y: =124
            ZIndex: =4

    Container4 As groupContainer.manualLayoutContainer:
        DropShadow: =DropShadow.Semilight
        Height: =298
        RadiusBottomLeft: =4
        RadiusBottomRight: =4
        RadiusTopLeft: =4
        RadiusTopRight: =4
        Width: =355
        X: =987
        Y: =213
        ZIndex: =5

        Rectangle4_1 As rectangle:
            BorderColor: =RGBA(0, 0, 0, 0)
            BorderStyle: =BorderStyle.None
            BorderThickness: =2
            DisabledFill: =RGBA(166, 166, 166, 1)
            Fill: =RGBA(237, 237, 237, 1)
            FocusedBorderThickness: =4
            Height: =56
            HoverFill: =RGBA(105, 121, 126, 1)
            PressedFill: =RGBA(105, 121, 126, 1)
            Width: =355
            ZIndex: =1

        Label18 As label:
            BorderColor: =RGBA(0, 0, 0, 0)
            BorderStyle: =BorderStyle.None
            BorderThickness: =2
            Color: =RGBA(51, 51, 51, 1)
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            DisabledColor: =RGBA(166, 166, 166, 1)
            FocusedBorderThickness: =4
            Font: =Font.'Segoe UI'
            FontWeight: =FontWeight.Semibold
            Height: =48
            Size: =17
            Text: ="Existing Cofiguration"
            Width: =275
            X: =13
            Y: =8
            ZIndex: =2

        Label16_1 As label:
            BorderColor: =RGBA(0, 0, 0, 0)
            BorderStyle: =BorderStyle.None
            BorderThickness: =2
            Color: =RGBA(51, 51, 51, 1)
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            DisabledColor: =RGBA(166, 166, 166, 1)
            FocusedBorderThickness: =4
            Font: =Font.'Segoe UI'
            Size: =13
            Text: |-
                ="Stakeholder:Supplier"
            Width: =191
            X: =13
            Y: =56
            ZIndex: =3

        Icon14_1 As icon.HorizontalLine:
            BorderColor: =RGBA(202, 202, 202, 1)
            BorderThickness: =1
            Color: =RGBA(202, 202, 202, 1)
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            DisabledColor: =RGBA(220, 220, 220, 1)
            DisabledFill: =RGBA(0, 0, 0, 0)
            FocusedBorderThickness: =4
            Height: =0
            HoverBorderColor: =RGBA(0, 0, 0, 0)
            HoverColor: =ColorFade(RGBA(105, 121, 126, 1), -30%)
            HoverFill: =RGBA(0, 0, 0, 0)
            Icon: =Icon.HorizontalLine
            PressedBorderColor: =RGBA(0, 0, 0, 0)
            PressedColor: =ColorFade(RGBA(105, 121, 126, 1), -30%)
            PressedFill: =RGBA(0, 0, 0, 0)
            Width: =328
            X: =13
            Y: =114
            ZIndex: =4

        Label16_2 As label:
            BorderColor: =RGBA(0, 0, 0, 0)
            BorderStyle: =BorderStyle.None
            BorderThickness: =2
            Color: =RGBA(51, 51, 51, 1)
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            DisabledColor: =RGBA(166, 166, 166, 1)
            FocusedBorderThickness: =4
            Font: =Font.'Segoe UI'
            Size: =13
            Text: |-
                ="Current Year:"
            Width: =191
            X: =13
            Y: =130
            ZIndex: =5

        Icon14_2 As icon.HorizontalLine:
            BorderColor: =RGBA(202, 202, 202, 1)
            BorderThickness: =1
            Color: =RGBA(202, 202, 202, 1)
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            DisabledColor: =RGBA(220, 220, 220, 1)
            DisabledFill: =RGBA(0, 0, 0, 0)
            FocusedBorderThickness: =4
            Height: =0
            HoverBorderColor: =RGBA(0, 0, 0, 0)
            HoverColor: =ColorFade(RGBA(105, 121, 126, 1), -30%)
            HoverFill: =RGBA(0, 0, 0, 0)
            Icon: =Icon.HorizontalLine
            PressedBorderColor: =RGBA(0, 0, 0, 0)
            PressedColor: =ColorFade(RGBA(105, 121, 126, 1), -30%)
            PressedFill: =RGBA(0, 0, 0, 0)
            Width: =328
            X: =13
            Y: =186
            ZIndex: =6

        Label19 As label:
            BorderColor: =RGBA(0, 0, 0, 0)
            BorderStyle: =BorderStyle.None
            BorderThickness: =2
            Color: =RGBA(51, 51, 51, 1)
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            DisabledColor: =RGBA(166, 166, 166, 1)
            FocusedBorderThickness: =4
            Font: =Font.'Segoe UI'
            Size: =13
            Text: |-
                ="Current Quarter:"
            X: =13
            Y: =206
            ZIndex: =7

        Icon14_3 As icon.HorizontalLine:
            BorderColor: =RGBA(202, 202, 202, 1)
            BorderThickness: =1
            Color: =RGBA(202, 202, 202, 1)
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            DisabledColor: =RGBA(220, 220, 220, 1)
            DisabledFill: =RGBA(0, 0, 0, 0)
            FocusedBorderThickness: =4
            Height: =0
            HoverBorderColor: =RGBA(0, 0, 0, 0)
            HoverColor: =ColorFade(RGBA(105, 121, 126, 1), -30%)
            HoverFill: =RGBA(0, 0, 0, 0)
            Icon: =Icon.HorizontalLine
            PressedBorderColor: =RGBA(0, 0, 0, 0)
            PressedColor: =ColorFade(RGBA(105, 121, 126, 1), -30%)
            PressedFill: =RGBA(0, 0, 0, 0)
            Width: =328
            X: =13
            Y: =266
            ZIndex: =8

