"'Configuration(com)' As CanvasComponent":
    Configurationcom_menu: |-
        =Table(
            {
                Title: "Upload Result",
                TargetScreen: App.ActiveScreen
            },
            {
                Title: "HACT Configuration",
                TargetScreen: App.ActiveScreen
            }
        )
    Currentscreen: ="Text"
    Fill: =RGBA(0, 0, 0, 0)
    Height: =500
    Width: =300
    X: =0
    Y: =0
    ZIndex: =1

    Gallery4 As gallery.galleryVertical:
        BorderColor: =RGBA(0, 18, 107, 1)
        DelayItemLoading: =true
        Height: =452
        Items: ='Configuration(com)'.Configurationcom_menu
        Layout: =Layout.Vertical
        LoadingSpinner: =LoadingSpinner.Data
        OnSelect: =true;Navigate(ThisItem.TargetScreen,ScreenTransition.None)
        TemplateSize: =49
        Width: =650
        X: =40
        Y: =37
        ZIndex: =1

        Label10 As label:
            BorderColor: =RGBA(0, 18, 107, 1)
            Color: =RGBA(0, 0, 0, 1)
            DisabledColor: =RGBA(166, 166, 166, 1)
            Height: =49
            HoverFill: =Color.LightBlue
            OnSelect: =Select(Parent)
            PaddingLeft: =50
            Size: =15
            Text: =ThisItem.Title
            Width: =256
            X: =10
            Y: =8
            ZIndex: =1

        Icon7 As icon.OptionsList:
            BorderColor: =RGBA(0, 18, 107, 1)
            DisabledBorderColor: =RGBA(166, 166, 166, 1)
            DisabledColor: =RGBA(244, 244, 244, 1)
            Height: =32
            Icon: =Icon.OptionsList
            OnSelect: =Select(Parent)
            Width: =20
            X: =20
            Y: =16
            ZIndex: =2

